# API Gateway Service
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  namespace: digital-tracking
  labels:
    app: api-gateway
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  - port: 443
    targetPort: 3000
    protocol: TCP
    name: https
  selector:
    app: api-gateway
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
---
# Auth Service
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: digital-tracking
  labels:
    app: auth-service
spec:
  type: ClusterIP
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
    name: http
  selector:
    app: auth-service
---
# User Service
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: digital-tracking
  labels:
    app: user-service
spec:
  type: ClusterIP
  ports:
  - port: 3002
    targetPort: 3002
    protocol: TCP
    name: http
  selector:
    app: user-service
---
# Chat Service
apiVersion: v1
kind: Service
metadata:
  name: chat-service
  namespace: digital-tracking
  labels:
    app: chat-service
spec:
  type: ClusterIP
  ports:
  - port: 3003
    targetPort: 3003
    protocol: TCP
    name: http
  - port: 3004
    targetPort: 3004
    protocol: TCP
    name: websocket
  selector:
    app: chat-service
---
# Todo Service
apiVersion: v1
kind: Service
metadata:
  name: todo-service
  namespace: digital-tracking
  labels:
    app: todo-service
spec:
  type: ClusterIP
  ports:
  - port: 3005
    targetPort: 3005
    protocol: TCP
    name: http
  selector:
    app: todo-service
---
# Notification Service
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: digital-tracking
  labels:
    app: notification-service
spec:
  type: ClusterIP
  ports:
  - port: 3009
    targetPort: 3009
    protocol: TCP
    name: http
  selector:
    app: notification-service
---
# Frontend Service
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: digital-tracking
  labels:
    app: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  - port: 443
    targetPort: 3000
    protocol: TCP
    name: https
  selector:
    app: frontend
---
# Mobile App Service
apiVersion: v1
kind: Service
metadata:
  name: mobile-app-service
  namespace: digital-tracking
  labels:
    app: mobile-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3002
    protocol: TCP
    name: http
  - port: 443
    targetPort: 3002
    protocol: TCP
    name: https
  selector:
    app: mobile-app
---
# PostgreSQL Database Service
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: digital-tracking
  labels:
    app: postgres
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgresql
  selector:
    app: postgres
---
# Redis Service
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: digital-tracking
  labels:
    app: redis
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: redis
  selector:
    app: redis
---
# Prometheus Service
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: digital-tracking
  labels:
    app: prometheus
spec:
  type: ClusterIP
  ports:
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: prometheus
  selector:
    app: prometheus
---
# Grafana Service
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: digital-tracking
  labels:
    app: grafana
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: grafana
  selector:
    app: grafana 