name: Local Development CI/CD - Free Forever

on:
  push:
    branches: [ main, develop, feature/* ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        default: 'test'
        type: choice
        options:
        - test
        - build
        - deploy-local
        - backup

env:
  NODE_VERSION: '18'
  DOCKER_COMPOSE_FILE: 'docker-compose.local.yml'

jobs:
  # Test Suite (FREE - GitHub Actions minutes)
  test:
    name: Run Tests (Free)
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        include:
          - name: Frontend Tests
            working-directory: ./
            test-command: npm test -- --watchAll=false --coverage --passWithNoTests
          - name: Backend Tests
            working-directory: ./backend
            test-command: npm run test:all
          - name: Mobile App Tests
            working-directory: ./WorkforceMobileExpo
            test-command: npm test -- --watchAll=false --passWithNoTests

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: ${{ matrix.working-directory }}/package-lock.json

    - name: Install dependencies
      run: |
        cd ${{ matrix.working-directory }}
        npm ci

    - name: Run tests
      run: |
        cd ${{ matrix.working-directory }}
        ${{ matrix.test-command }}

    - name: Upload coverage to Codecov (FREE)
      if: matrix.name == 'Frontend Tests'
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage/lcov.info
        flags: frontend
        name: frontend-coverage

  # Security Scan (FREE)
  security-scan:
    name: Security Scan (Free)
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install dependencies
      run: |
        npm ci
        cd backend && npm ci

    - name: Run npm audit (FREE)
      run: |
        npm audit --audit-level=moderate
        cd backend && npm audit --audit-level=moderate

    - name: Run Snyk security scan (FREE)
      uses: snyk/actions/node@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --severity-threshold=high --all-projects

    - name: Run Trivy vulnerability scanner (FREE)
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest'
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Upload Trivy scan results to GitHub Security tab (FREE)
      uses: github/codeql-action/upload-sarif@v2
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'

  # Build Docker Images (FREE)
  build:
    name: Build Docker Images (Free)
    runs-on: ubuntu-latest
    needs: [test, security-scan]
    
    strategy:
      matrix:
        include:
          - name: Frontend
            context: ./
            dockerfile: Dockerfile.frontend
            image: frontend
          - name: Backend
            context: ./backend
            dockerfile: Dockerfile
            image: backend
          - name: API Gateway
            context: ./api-gateway
            dockerfile: Dockerfile
            image: api-gateway
          - name: Mobile App
            context: ./WorkforceMobileExpo
            dockerfile: Dockerfile
            image: mobile-app

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry (FREE)
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository }}/${{ matrix.image }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=sha,prefix={{branch}}-

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ${{ matrix.context }}
        file: ${{ matrix.context }}/${{ matrix.dockerfile }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  # Local Deployment Instructions (FREE)
  deploy-local:
    name: Deploy to Local Environment (Free)
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'deploy-local'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Generate deployment instructions
      run: |
        echo "## 🚀 Local Deployment Instructions" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "Your Docker images have been built and pushed to GitHub Container Registry." >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### To deploy locally on your Mac:" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "1. **Pull the latest images:**" >> $GITHUB_STEP_SUMMARY
        echo "   \`\`\`bash" >> $GITHUB_STEP_SUMMARY
        echo "   docker pull ghcr.io/${{ github.repository }}/frontend:latest" >> $GITHUB_STEP_SUMMARY
        echo "   docker pull ghcr.io/${{ github.repository }}/backend:latest" >> $GITHUB_STEP_SUMMARY
        echo "   docker pull ghcr.io/${{ github.repository }}/api-gateway:latest" >> $GITHUB_STEP_SUMMARY
        echo "   docker pull ghcr.io/${{ github.repository }}/mobile-app:latest" >> $GITHUB_STEP_SUMMARY
        echo "   \`\`\`" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "2. **Start local environment:**" >> $GITHUB_STEP_SUMMARY
        echo "   \`\`\`bash" >> $GITHUB_STEP_SUMMARY
        echo "   ./devops/scripts/local-setup.sh start" >> $GITHUB_STEP_SUMMARY
        echo "   \`\`\`" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "3. **Access your application:**" >> $GITHUB_STEP_SUMMARY
        echo "   - Frontend: http://localhost:3000" >> $GITHUB_STEP_SUMMARY
        echo "   - API Gateway: http://localhost:8080" >> $GITHUB_STEP_SUMMARY
        echo "   - Grafana: http://localhost:3001 (admin/admin)" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Alternative: Use local Docker Compose" >> $GITHUB_STEP_SUMMARY
        echo "   \`\`\`bash" >> $GITHUB_STEP_SUMMARY
        echo "   docker-compose -f docker-compose.local.yml up -d" >> $GITHUB_STEP_SUMMARY
        echo "   \`\`\`" >> $GITHUB_STEP_SUMMARY

    - name: Create deployment artifact
      run: |
        mkdir -p deployment-instructions
        cat > deployment-instructions/README.md << 'EOF'
        # Local Deployment Instructions
        
        ## Quick Start
        1. Run: `./devops/scripts/local-setup.sh start`
        2. Access: http://localhost:3000
        
        ## Manual Steps
        1. Pull images from GitHub Container Registry
        2. Start Docker Compose: `docker-compose -f docker-compose.local.yml up -d`
        3. Check health: `./devops/scripts/local-setup.sh health`
        
        ## Monitoring
        - Grafana: http://localhost:3001 (admin/admin)
        - Prometheus: http://localhost:9090
        - Database Admin: http://localhost:8081
        
        ## Troubleshooting
        - View logs: `./devops/scripts/local-setup.sh logs`
        - Check status: `./devops/scripts/local-setup.sh status`
        - Restart: `./devops/scripts/local-setup.sh restart`
        EOF

    - name: Upload deployment instructions
      uses: actions/upload-artifact@v4
      with:
        name: deployment-instructions
        path: deployment-instructions/

  # Local Backup Instructions (FREE)
  backup:
    name: Backup Instructions (Free)
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'backup'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Generate backup instructions
      run: |
        echo "## 💾 Local Backup Instructions" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Automated Backup" >> $GITHUB_STEP_SUMMARY
        echo "   \`\`\`bash" >> $GITHUB_STEP_SUMMARY
        echo "   ./devops/scripts/local-setup.sh backup" >> $GITHUB_STEP_SUMMARY
        echo "   \`\`\`" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Manual Database Backup" >> $GITHUB_STEP_SUMMARY
        echo "   \`\`\`bash" >> $GITHUB_STEP_SUMMARY
        echo "   docker exec postgres-local pg_dump -U workforce_user workforce_db > backup.sql" >> $GITHUB_STEP_SUMMARY
        echo "   \`\`\`" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Backup to GitHub Releases (FREE)" >> $GITHUB_STEP_SUMMARY
        echo "   \`\`\`bash" >> $GITHUB_STEP_SUMMARY
        echo "   tar -czf backup.tar.gz backup.sql" >> $GITHUB_STEP_SUMMARY
        echo "   gh release upload v1.0.0 backup.tar.gz" >> $GITHUB_STEP_SUMMARY
        echo "   \`\`\`" >> $GITHUB_STEP_SUMMARY

  # Performance Testing (FREE)
  performance:
    name: Performance Tests (Free)
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Install Artillery (FREE)
      run: npm install -g artillery

    - name: Run load tests
      run: |
        # Create a simple load test
        cat > load-test.yml << 'EOF'
        config:
          target: 'http://localhost:3000'
          phases:
            - duration: 60
              arrivalRate: 10
        scenarios:
          - name: "Load test"
            requests:
              - get:
                  url: "/"
        EOF
        
        echo "Load test configuration created"
        echo "Run locally: artillery run load-test.yml"

    - name: Run Lighthouse CI (FREE)
      uses: treosh/lighthouse-ci-action@v10
      with:
        urls: |
          http://localhost:3000
        uploadArtifacts: true
        temporaryPublicStorage: true

  # Documentation Update (FREE)
  docs:
    name: Update Documentation (Free)
    runs-on: ubuntu-latest
    needs: [test, build]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Generate documentation
      run: |
        echo "## 📚 Documentation Updated" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Local Development Guide" >> $GITHUB_STEP_SUMMARY
        echo "- [Local Setup Guide](devops/local-devops-setup.md)" >> $GITHUB_STEP_SUMMARY
        echo "- [DevOps Documentation](devops/README.md)" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Quick Commands" >> $GITHUB_STEP_SUMMARY
        echo "- Start: \`./devops/scripts/local-setup.sh start\`" >> $GITHUB_STEP_SUMMARY
        echo "- Stop: \`./devops/scripts/local-setup.sh stop\`" >> $GITHUB_STEP_SUMMARY
        echo "- Logs: \`./devops/scripts/local-setup.sh logs\`" >> $GITHUB_STEP_SUMMARY
        echo "- Health: \`./devops/scripts/local-setup.sh health\`" >> $GITHUB_STEP_SUMMARY

  # Summary Report (FREE)
  summary:
    name: Generate Summary Report (Free)
    runs-on: ubuntu-latest
    needs: [test, security-scan, build, performance, docs]
    if: always()
    
    steps:
    - name: Generate summary
      run: |
        echo "## 🎉 Local DevOps Pipeline Complete!" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### ✅ What's Ready:" >> $GITHUB_STEP_SUMMARY
        echo "- **Tests**: All tests passed" >> $GITHUB_STEP_SUMMARY
        echo "- **Security**: Vulnerability scan completed" >> $GITHUB_STEP_SUMMARY
        echo "- **Build**: Docker images built and pushed" >> $GITHUB_STEP_SUMMARY
        echo "- **Performance**: Load tests configured" >> $GITHUB_STEP_SUMMARY
        echo "- **Documentation**: Updated guides" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### 🚀 Next Steps:" >> $GITHUB_STEP_SUMMARY
        echo "1. Pull the latest images on your Mac" >> $GITHUB_STEP_SUMMARY
        echo "2. Run: \`./devops/scripts/local-setup.sh start\`" >> $GITHUB_STEP_SUMMARY
        echo "3. Access: http://localhost:3000" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### 💰 Cost: $0/month" >> $GITHUB_STEP_SUMMARY
        echo "- GitHub Actions: FREE (2000 minutes/month)" >> $GITHUB_STEP_SUMMARY
        echo "- GitHub Container Registry: FREE" >> $GITHUB_STEP_SUMMARY
        echo "- Local Infrastructure: FREE" >> $GITHUB_STEP_SUMMARY
        echo "- Monitoring: FREE" >> $GITHUB_STEP_SUMMARY 